info:
  system_id: False
  simulation_id: False
  use_plinder_index: True
  bound_state: False
  
# Preprocessing parameters
preprocessing:
  process_protein: true             # Process the protein with PDBFixer  
  process_ligand: true              # Process the ligand with OpenFF
  add_solvent: true                 # Add Solvent to the system, Default: True
  ionic_strength: 0.15              # Molar
  box_padding: 1.0                  # nm

# Forcefield parameters
forcefield:
  proteinFF: "amber14-all.xml"
  nucleicFF: "amber14/DNA.OL15.xml"
  ligandFF: "gaff-2.11"
  waterFF: "amber14/tip3pfb.xml"
  water_model: "tip3p"
  forcefield_kwargs:
    rigidWater: True
    removeCMMotion: False
    hydrogenMass: 1.5              # amu

# Simulation parameters
simulation_params:
  backbone_restraint_force: 100.0     # kcal/mol/A^2
  platform:
    type: "CUDA"
    devices: '0'
  warmup:
    init_temp: 50.0                   # K - the starting temperature
    final_temp: 300.0                 # K - the final temperature
    friction: 1.0                     # ps^-1 - the friction coefficient
    time_step: 2.0                    # fs - the time step
    heating_step: 100                 # how many steps to WarmUp Simulation by 1K
    checkpoint_interval: 100
    trajectory_interval: 100
    state_data_reporter_interval: 100
  backbone_removal:
    temp: 300.0
    friction: 1.0
    time_step: 2.0
    nsteps: 500000
    nloops: 100
    checkpoint_interval: 1000
    trajectory_interval: 1000
    state_data_reporter_interval: 1000
  nvt:
    temp: 300.0
    friction: 1.0
    time_step: 2.0
    nsteps: 500000
    checkpoint_interval: 1000
    trajectory_interval: 1000
    state_data_reporter_interval: 1000
  npt:
    temp: 300.0
    pressure: 1.0
    friction: 1.0
    time_step: 2.0
    nsteps: 500000
    checkpoint_interval: 1000
    trajectory_interval: 1000
    state_data_reporter_interval: 1000
  production:
    temp: 300.0
    pressure: 1.0
    friction: 1.0
    time_step: 2.0
    nsteps: 5000000
    checkpoint_interval: 1000
    trajectory_interval: 1000
    state_data_reporter_interval: 1000

# File paths and formats
paths:
  raw_protein_files: False
  raw_ligand_files: False
  output_dir: False



